{% set version = "1.2.1" %}

package:
  name: go-licenses
  version: {{ version }}

source:
  - url: https://github.com/google/go-licenses/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 0757c90cda8a1cd0969869180ce06109347711e7c5023b429b4a0b77cced674b

build:
  number: 1

requirements:
  build:
    - {{ compiler('go') }}
    - posix  # [win]
  host:
  run:
    - go

test:
  commands:
    - git clone --depth=1 "https://github.com/google/go-licenses"
    - cd go-licenses
    - go-licenses csv . | findstr "Apache-2.0 BSD-.-Clause MIT"             # [win]
    - go-licenses csv . | grep 'Apache-2\.0\|BSD-.-Clause\|MIT\|Unlicense'  # [not win]
  requires:
    - git
    - go

about:
  home: https://github.com/google/go-licenses
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - license-files/
  summary: A tool to collect licenses from the dependency tree of a Go package in order to comply with redistribution terms.

extra:
  recipe-maintainers:
    - dhirschfeld
    - mbargull
    - bollwyvl
