{% set version = "2.0.0" %}

package:
  name: go-licenses
  version: {{ version }}

source:
  - url: https://github.com/google/go-licenses/archive/refs/tags/v{{ version }}.tar.gz
    sha256: b1dea2846510f7ce464902f7dacf13e896093ac2cbf6a7794bdde9457e5ff977

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - posix  # [win]
  host:
  run:
    - go

test:
  commands:
    - git clone --depth=1 "https://github.com/google/go-licenses"
    - cd go-licenses
    - go-licenses csv . | findstr "Apache-2.0 BSD-.-Clause MIT"             # [win]
    - go-licenses csv . | grep 'Apache-2\.0\|BSD-.-Clause\|MIT\|Unlicense'  # [not win]
  requires:
    - git
    - go

about:
  home: https://github.com/google/go-licenses
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - license-files/
  summary: A tool to collect licenses from the dependency tree of a Go package in order to comply with redistribution terms.

extra:
  recipe-maintainers:
    - dhirschfeld
    - mbargull
    - bollwyvl
